name: Publish

on: [push, pull_request]

jobs:

  build:
    name: Build
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install .
      - name: Build package
        run: |
          python -m build

  test:
    name: Tests
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test]"
      - name: Run tests
        run: |
          python -m pytest
      - name: Run tests and coverage
        if: |
          matrix.python-version == '3.11' &&
          matrix.os == 'ubuntu-latest'
        run: |
          coverage run -m pytest
          coverage xml
      - name: Upload coverage reports to Codecov
        if: |
          matrix.python-version == '3.11' &&
          matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          verbose: true
          token: ${{secrets.CODECOV_TOKEN}}

  pre-commit:
    name: Pre-commit
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      - name: Install python dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"
      - name: Run pre-commits
        run: |
          pre-commit install
          pre-commit run --all-files

  # check docs build and render (no deployment)
  docs-build:
    name: Build Docs
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      - name: Install python dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[docs]"
      - name: Build API reference pages
        run: |
          python -m quartodoc build
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render docs
        run: |
          quarto render
